"""Location..

Revision ID: d47874da32f5
Revises: 997d43e73ade
Create Date: 2019-10-03 12:22:56.663358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47874da32f5'
down_revision = '997d43e73ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('fullname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mobile_phone', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('office_phone', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_email_address'), 'users', ['email_address'], unique=True)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'tel')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_email_address'), table_name='users')
    op.drop_column('users', 'office_phone')
    op.drop_column('users', 'mobile_phone')
    op.drop_column('users', 'fullname')
    op.drop_column('users', 'email_address')
    # ### end Alembic commands ###
